/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.connection;

/**
 *
 * @author Lenovo
 */
public class formPasien extends javax.swing.JFrame {

    /**
     * Creates new form formPasien
     */
    public formPasien() {
        initComponents();
        tampiltabel();
    }
    
    private DefaultTableModel tabmode;
    private Connection conn = new connection().connect();
    private Statement st;
    private String tgl;
    private ResultSet rs;
   
   
    
    private void clear(){
        nik.setText("");
        jcKepesertaan.setSelectedItem("");
        noFaskes.setText("");
        namaPasien.setText("");
        tempat.setText("");
        umur.setText("");
        buttonGroup1.clearSelection();
        alamat.setText("");
        tanggalLahir.setDate(null);
        simpan.setEnabled(true);
    }
  
    
     private void tampiltabel() {
         Object[] Baris ={"NIK","Jenis Kepesertaan","No Faskes","Nama Pasien","Jenis Kelamin","Tempat","Tanggal Lahir","Umur","Alamat"};
    tabmode = new DefaultTableModel(null,Baris);
    tablePasien.setModel(tabmode);
    String sql = "select * from pasien ORDER BY nik ASC";;
    try {
        
        java.sql.Statement stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while(rs.next()){
            String a=rs.getString("nik");
            String b=rs.getString("jenisKepesertaan");
            String c=rs.getString("noFaskes");
            String d=rs.getString("namaPasien");
            String e=rs.getString("jenisKelamin");
            String f=rs.getString("tempat");
            String g=rs.getString("tanggalLahir");
            String h=rs.getString("umur");
            String i=rs.getString("alamat");
           
           
            
            String[] data={a,b,c,d,e,f,g,h,i};
            tabmode.addRow(data);
            
        }
    } catch (Exception e){
        System.out.print(e);
    }
    }
                 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        noFaskes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcKepesertaan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        namaPasien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        RbL = new javax.swing.JRadioButton();
        RbP = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tempat = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        umur = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 218, 220));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 42, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Pasien");

        nik.setBackground(new java.awt.Color(168, 218, 220));
        nik.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        nik.setForeground(new java.awt.Color(23, 42, 58));
        nik.setBorder(null);
        nik.setCaretColor(new java.awt.Color(23, 42, 58));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("NIK");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        noFaskes.setBackground(new java.awt.Color(168, 218, 220));
        noFaskes.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        noFaskes.setForeground(new java.awt.Color(23, 42, 58));
        noFaskes.setBorder(null);
        noFaskes.setCaretColor(new java.awt.Color(23, 42, 58));
        noFaskes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noFaskesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("No. Faskes/Bpjs");

        jcKepesertaan.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jcKepesertaan.setForeground(new java.awt.Color(51, 51, 51));
        jcKepesertaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BPJS", "UMUM" }));
        jcKepesertaan.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Jenis Kepesertaan");

        namaPasien.setBackground(new java.awt.Color(168, 218, 220));
        namaPasien.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        namaPasien.setForeground(new java.awt.Color(23, 42, 58));
        namaPasien.setBorder(null);
        namaPasien.setCaretColor(new java.awt.Color(23, 42, 58));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nama Pasien");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Jenis Kelamin");

        RbL.setBackground(new java.awt.Color(168, 218, 220));
        buttonGroup1.add(RbL);
        RbL.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RbL.setText("Pria");
        RbL.setBorder(null);
        RbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbLActionPerformed(evt);
            }
        });

        RbP.setBackground(new java.awt.Color(168, 218, 220));
        buttonGroup1.add(RbP);
        RbP.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RbP.setText("Wanita");
        RbP.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Tempat");

        tempat.setBackground(new java.awt.Color(168, 218, 220));
        tempat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        tempat.setForeground(new java.awt.Color(23, 42, 58));
        tempat.setBorder(null);
        tempat.setCaretColor(new java.awt.Color(23, 42, 58));
        tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tanggal Lahir");

        tanggalLahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalLahirPropertyChange(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Alamat");

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        alamat.setRows(5);
        alamat.setBorder(null);
        jScrollPane1.setViewportView(alamat);

        simpan.setBackground(new java.awt.Color(0, 102, 255));
        simpan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.setBorder(null);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(0, 0, 0));
        ubah.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        ubah.setText("Ubah");
        ubah.setBorder(null);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton3.setText("Hapus");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasien.setGridColor(new java.awt.Color(255, 255, 255));
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePasien);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Umur");

        umur.setBackground(new java.awt.Color(168, 218, 220));
        umur.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        umur.setForeground(new java.awt.Color(23, 42, 58));
        umur.setBorder(null);
        umur.setCaretColor(new java.awt.Color(23, 42, 58));
        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(umur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbL, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel8))
                                    .addComponent(RbP)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tempat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(namaPasien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcKepesertaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(noFaskes, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nik, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89)
                                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcKepesertaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noFaskes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RbL)
                            .addComponent(RbP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(tanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbLActionPerformed

    private void tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatActionPerformed

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void noFaskesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noFaskesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noFaskesActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
         // TODO add your handling code here:
          String JK;
        if (RbL.isSelected()) {
        JK = "Pria";
        } else {
        JK = "Wanita";
        }
         
         String sql = "Insert into pasien values (?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement (sql);
            stat.setString (1, nik.getText());
            stat.setString (2, jcKepesertaan.getSelectedItem().toString());
            stat.setString (3, noFaskes.getText());
            stat.setString (4, namaPasien.getText());
            stat.setString (5, JK);
            stat.setString (6, tempat.getText());
            stat.setString (7, tgl);
            stat.setString (8, umur.getText());
            stat.setString (9, alamat.getText());
           

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampiltabel();
            clear();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
 
        String JK;
        if (RbL.isSelected()) {
        JK = "Pria";
        } else {
        JK = "Wanita";
        }
        
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update pasien set nik=?,jenisKepesertaan=?,noFaskes=?,namaPasien=?,jenisKelamin=?,tempat=?,tanggalLahir=?,umur=?,alamat=? where nik='"+nik.getText().toString()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            if(ok==0)
            {
                try
                {
                    st.setString(1,nik.getText());
                    st.setString(2,jcKepesertaan.getSelectedItem().toString());
                    st.setString(3,noFaskes.getText());
                    st.setString(4,namaPasien.getText());
                    st.setString(5,JK);
                    st.setString(6,tempat.getText());
                    st.setString(7,tgl);
                    st.setString(8,umur.getText());
                    st.setString(9,alamat.getText());

                    st.executeUpdate();

                    clear();
                    tampiltabel();
                    
                    JOptionPane.showMessageDialog(null,"Update Data Sukses");
                }catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }

            }
        }catch (Exception e){}
    }//GEN-LAST:event_ubahActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int row = tablePasien.getSelectedRow();
        DefaultTableModel model= (DefaultTableModel)tablePasien.getModel();

        String selected = model.getValueAt(row, 0).toString();

        if (row >= 0)
        {

           
            try {
    
                PreparedStatement ps = conn.prepareStatement("delete from pasien where nik='"+selected+"' ");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
              
                tampiltabel();
                  clear();
                 
            }
            catch (Exception w) {
                JOptionPane.showMessageDialog(this, "Connection Error!");
            }
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tanggalLahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalLahirPropertyChange
        // TODO add your handling code here:
         if (tanggalLahir.getDate()!=null){
            SimpleDateFormat fmt= new SimpleDateFormat("yyyy-MM-dd");
            tgl=fmt.format (tanggalLahir.getDate());}
    }//GEN-LAST:event_tanggalLahirPropertyChange

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        // TODO add your handling code here:
        
          int choose = tablePasien.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tablePasien.getModel();
        simpan.setEnabled(false);

        // get the selected row index
        int selectedRowIndex = tablePasien.getSelectedRow();

        // set the selected row data into jtextfields
        nik.setText(model.getValueAt(selectedRowIndex, 0).toString());
        Object obj = tablePasien.getValueAt(tablePasien.getSelectedRow(), 1);
       jcKepesertaan.setSelectedItem(obj);
        noFaskes.setText(model.getValueAt(selectedRowIndex, 2).toString());
        namaPasien.setText(model.getValueAt(selectedRowIndex, 3).toString());
         String jenkel = model.getValueAt(choose, 4).toString();
            if(jenkel.equals("Pria")){
                RbL.setSelected(true);
            }
            else {
                RbP.setSelected(true);
            }
         String s=(String)tablePasien.getModel().getValueAt(choose, 6);
        try{
        SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date d=f.parse(s);
        tanggalLahir.setDate(d);
        }catch(Exception ex){
         ex.printStackTrace();
        }  
        
        tempat.setText(model.getValueAt(selectedRowIndex, 5).toString());
        umur.setText(model.getValueAt(selectedRowIndex, 7).toString());
        alamat.setText(model.getValueAt(selectedRowIndex, 8).toString());
        
    }//GEN-LAST:event_tablePasienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbL;
    private javax.swing.JRadioButton RbP;
    private javax.swing.JTextArea alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcKepesertaan;
    private javax.swing.JTextField namaPasien;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField noFaskes;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tablePasien;
    private com.toedter.calendar.JDateChooser tanggalLahir;
    private javax.swing.JTextField tempat;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
